### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by mecheann** [MuhammadRafeh/react-native-datatable-component#22]
Is there a way to set the number of rows per page?

**Comment by MuhammadRafeh** [comment]
Hi, for now there's no feature like this. But will implement soon.

**Comment by KrisLau** [comment]
@mecheann You can do this by taking the length of your data array and dividing it by the number of rows you want per page. So if you have 10 items in your data array and want 5 rows per page, just set the `noOfPages` prop to 10/5.

**Comment by mecheann** [comment]
@KrisLau Thank you for taking the time to response
