### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by KrisLau** [MuhammadRafeh/react-native-datatable-component#24]
Hi I made a [feature request](https://github.com/react-native-elements/react-native-elements/issues/3793) to the UI library I use to integrate something similar to this with a write up on improvement suggestions. I figured I should repost those suggestions here in case anyone is interested or if @MuhammadRafeh would be interested in implementing any of these:

> I think something like [`react-native-datatable-component`](https://github.com/MuhammadRafeh/react-native-datatable-component) with more customizability (ability to change icons & icon position) or maybe add features like filtering, locking some columns and rows so that those are pinned / don't scroll. Would also be extremely helpful to have horizontal scrolling for the columns if they are more than the width of the screen ([current workaround](https://github.com/MuhammadRafeh/react-native-datatable-component/issues/16#issuecomment-1563402969) isnt terrible though).
> 
> Also I think it would be good to remove the prop `colNames` and `colSettings` as they are redundant. It should be replaced by the prop name `columns` and the input should be the same as `colSettings`.  
> 
> Example of implementation:
> ```js
> import React from 'react';
> import DataTable, { COL_TYPES } from 'react-native-datatable-component';
> 
> const SomeComponent = props => {
>     return (
>         <DataTable
>             data={[ 
>                 { name: 'Muhammad Rafeh', age: 21, gender: 'male' },
>                 { name: 'Muhammad Akif', age: 22, gender: 'male' },
>                 { name: 'Muhammad Umar', age: 21, gender: 'male' },
>                 { name: 'Amna Shakeel', age: 22, gender: 'female' },
>                 { name: 'Muhammad Ammar', age: 20, gender: 'male' },
>                 { name: 'Muhammad Moiz', age: 13, gender: 'male' }
>             ]}
>             // original props that should be removed
>             /* colNames={['name', 'age', 'gender']}
>             colSettings={[
>               { name: 'name', type: COL_TYPES.STRING, width: '40%' }, 
>               { name: 'age', type: COL_TYPES.INT, width: '30%' }, 
>               {name: 'gender', type: COL_TYPES.STRING, width: '30%'}
>             ]}
>             pages={2} */
>            columns={[
>               { name: 'name', type: COL_TYPES.STRING, width: '40%' }, 
>               { name: 'age', type: COL_TYPES.INT, width: '30%' }, 
>               {name: 'gender', type: COL_TYPES.STRING, width: '30%'}
>             ]}
>             rowsPerPage={10}
>             backgroundColor={'rgba(23,2,4,0.2)'} 
>             headerLabelStyle={{ color: 'grey', fontSize: 12 }} 
>         />
>     );
> }
> 
> export default SomeComponent;
> ```
> `doSort` should also be renamed to just `sort` I think and the sorting icon should indicate if it is sorted by ascending or descending order

**Comment by KrisLau** [comment]
Made some changes to accommodate my requirements which I might submit as a PR but it will probably need to be tested and tweaked to make sure it doesn't break existing functionality for other people.

**Comment by MuhammadRafeh** [comment]
Thanks and Sure @KrisLau

**Comment by KrisLau** [comment]
@MuhammadRafeh Done and created the pull request:

- https://github.com/MuhammadRafeh/react-native-datatable-component/pull/25

**Comment by KrisLau** [comment]
Closing this since the PR was merged

**Comment by MuhammadRafeh** [comment]
Sure @KrisLau . I would like to invite you to work on this repository, perhaps by converting this project to TypeScript and starting work on closing the currently open issues. If you are interested, I can add you as a collaborator in this repo as well.

**Comment by KrisLau** [comment]
@MuhammadRafeh I've never used TypeScript so I wouldn't be able to really help with that! I'll probably pass on being a collaborator since I dont really have the time for it right now but I'll def make some PRs to help whenever I have time.

I was already thinking of working on:

- https://github.com/MuhammadRafeh/react-native-datatable-component/issues/23

**Comment by MuhammadRafeh** [comment]
@KrisLau  Sure, no problem. I also don't have enough time to maintain the repo. But I will implement TypeScript soon. Thanks a lot for your contribution. Keep going on.

**Comment by WangShayne** [comment]
custom header col name #4 
some no english app will be need this
