### ISSUE TITLE
spaces in column's name are not allowed

### ISSUE THREAD

**Issue by AwaisBinKaleem** [MuhammadRafeh/react-native-datatable-component#6]
when column name is long string with spaces it should be moved to new line just like auto wrap property in css.

**Comment by MuhammadRafeh** [comment]
Thanks for letting me know. I will do this soon and then let you know. If you can do this then it's welcome!

**Comment by MuhammadRafeh** [comment]
Thanks @AwaisBinKaleem for the Pr, I merged. If you want any other feature, you're welcome.

**Comment by MuhammadRafeh** [comment]
You can now test.

**Comment by AwaisBinKaleem** [comment]
just tested that. here is screen shot attached.

![cols](https://user-images.githubusercontent.com/51041559/155110811-8e6110d8-8662-4ecf-b3c0-fb62141f25a5.png)

it is resizing font size and still spaces in column names are not allowed.
but it is some how better then previous version.

it looks like that is due to revert commit in it.

**Comment by MuhammadRafeh** [comment]
Ok. Let me check. Can you send me this data?

**Comment by AwaisBinKaleem** [comment]
sure...!
`<DataTable
                data={[
                    {id:1, Trade_No_hello: '1', Fee: 21, PL_percent: 'male', PL_USD: 'male', New_Balance: 'male' },
                    {id:2, Trade_No_hello: '2', Fee: 22, PL_percent: 'male', PL_USD: 'male', New_Balance: 'male' },
                    {id:3, Trade_No_hello: '3', Fee: 21, PL_percent: 'male', PL_USD: 'male', New_Balance: 'male' },
                    {id:4, Trade_No_hello: '4', Fee: 22, PL_percent: 'female', PL_USD: 'male', New_Balance: 'male' },
                    {id:5, Trade_No_hello: '5', Fee: 20, PL_percent: 'male', PL_USD: 'male', New_Balance: 'male' },
                    {id:6, Trade_No_hello: '6', Fee: 13, PL_percent: 'male', PL_USD: 'male', New_Balance: 'male' },
                    {id:7, Trade_No_hello: '7', Fee: 22, PL_percent: 'female', PL_USD: 'male', New_Balance: 'male' },
                    {id:8, Trade_No_hello: '8', Fee: 20, PL_percent: 'male', PL_USD: 'male', New_Balance: 'male' },
                    {id:9, Trade_No_hello: '9', Fee: 13, PL_percent: 'male', PL_USD: 'male', New_Balance: 'male' }
                ]} // list of objects
                colNames={['Trade_No_hello', 'Fee', 'PL_percent', 'PL_USD', 'New_Balance']} //List of Strings
                colSettings={[{ name: 'Trade_No_hello', type: COL_TYPES.INT },
                { name: 'Fee', type: COL_TYPES.STRING },
                { name: 'PL_percent', type: COL_TYPES.STRING },
                { name: 'PL_USD', type: COL_TYPES.STRING },
                { name: 'New_Balance', type: COL_TYPES.INT },]}//List of Objects
                noOfPages={1} //number
                backgroundColor={'rgba(211,211,211,0.3)'} //Table Background Color
            />`

**Comment by MuhammadRafeh** [comment]
Thanks dude! Let me check this and will inform you shortly!

**Comment by AwaisBinKaleem** [comment]
> Thanks dude! Let me check this and will inform you shortly!

dude you can cherry-pick my commit to save your time if needed.

**Comment by MuhammadRafeh** [comment]
I updated code, now check plz.

**Comment by MuhammadRafeh** [comment]
@AwaisBinKaleem  I can pick that code but there are very few cases for these datas. That's why I am not taking, If I take that it should increase props and no one will use that except few.

But I corrected now, checkout and let me know, Now spaces will move you to the next line, You can remove underscore from your column names now !!!

**Comment by MuhammadRafeh** [comment]
![Screenshot_20220222_172844_host.exp.exponent.jpg](https://user-images.githubusercontent.com/61616929/155132574-2fe187da-cc93-40d2-b58a-657e4224de2f.jpg)

Now checkout this.

**Comment by MuhammadRafeh** [comment]
Now checkout, you have nice header with spaces

![Screenshot_20220222_173304_host.exp.exponent.jpg](https://user-images.githubusercontent.com/61616929/155133397-7804bad4-72b8-44b6-a15a-55abb83ffbaf.jpg)

**Comment by MuhammadRafeh** [comment]
@AwaisBinKaleem Let me know if this problem still exists?

**Comment by AwaisBinKaleem** [comment]
> Now checkout, you have nice header with spaces
> 
> ![Screenshot_20220222_173304_host.exp.exponent.jpg](https://user-images.githubusercontent.com/61616929/155133397-7804bad4-72b8-44b6-a15a-55abb83ffbaf.jpg)

LGTM

can you send mn data for this...!

**Comment by AwaisBinKaleem** [comment]
i am little bit confusuing to use this.
should i have to use props like this?
`data[{first name : "Ali" }} prop that should be same as colNames['first name']`
because key of **data** is **not** string but value of **colNames** is string.

**Comment by MuhammadRafeh** [comment]
```js
<DataTable
        data={[
          { id: 1, 'Trade No Hello': '1', Fee: 21, 'PL Percent': 'male', 'PL USD': 'male', 'New Balance': 'male' },
          { id: 2, 'Trade No Hello': '2', Fee: 22, 'PL Percent': 'male', 'PL USD': 'male', 'New Balance': 'male' },
          { id: 3, 'Trade No Hello': '3', Fee: 21, 'PL Percent': 'male', 'PL USD': 'male', 'New Balance': 'male' },
          { id: 4, 'Trade No Hello': '4', Fee: 22, 'PL Percent': 'female', 'PL USD': 'male', 'New Balance': 'male' },
          { id: 5, 'Trade No Hello': '5', Fee: 20, 'PL Percent': 'male', 'PL USD': 'male', 'New Balance': 'male' },
          { id: 6, 'Trade No Hello': '6', Fee: 13, 'PL Percent': 'male', 'PL USD': 'male', 'New Balance': 'male' },
          { id: 7, 'Trade No Hello': '7', Fee: 22, 'PL Percent': 'female', 'PL USD': 'male', 'New Balance': 'male' },
          { id: 8, 'Trade No Hello': '8', Fee: 20, 'PL Percent': 'male', 'PL USD': 'male', 'New Balance': 'male' },
          { id: 9, 'Trade No Hello': '9', Fee: 13, 'PL Percent': 'male', 'PL USD': 'male', 'New Balance': 'male' }
        ]} // list of objects
        colNames={['Trade No Hello', 'Fee', 'PL Percent', 'PL USD', 'New Balance']} //List of Strings
        colSettings={[{ name: 'Trade No Hello', type: COL_TYPES.INT },
        { name: 'Fee', type: COL_TYPES.STRING },
        { name: 'PL Percent', type: COL_TYPES.STRING },
        { name: 'PL USD', type: COL_TYPES.STRING },
        { name: 'New Balance', type: COL_TYPES.INT },]}//List of Objects
        noOfPages={1} //number
        backgroundColor={'rgba(211,211,211,0.3)'} //Table Background Color
      />
```

**Comment by AwaisBinKaleem** [comment]
thanks dude i got the point.
key is ni single quotes.

it is working fine now.

**Comment by MuhammadRafeh** [comment]
> i am little bit confusuing to use this. should i have to use props like this? `data[{first name : "Ali" }} prop that should be same as colNames['first name']` because key of **data** is **not** string but value of **colNames** is string.
> 
> as space is allowed in string value not in the key of object

Just wrap column name in string in everyplace. In objects keys you also have to do the same!!!
I hope you got it!
