### ISSUE TITLE
Can someone tell me How to remove sorting option from DataTables? Like sorting arrows 

### ISSUE THREAD

**Issue by wasi-sketch** [MuhammadRafeh/react-native-datatable-component#9]

**Comment by MuhammadRafeh** [comment]
Let me implement this feature for you.

**Comment by wasi-sketch** [comment]
Yes please sir kindly do it

**Comment by MuhammadRafeh** [comment]
Please download latest version of this Module and use doSort prop in order to avoid sorting. 
```js
doSort={false}
```

**Comment by MuhammadRafeh** [comment]
And please let me know if this problem still exists!

**Comment by wasi-sketch** [comment]
Ok sir i will try it and inform you if it does not work

**Comment by wasi-sketch** [comment]
Can you please give me a favor actually my text for tables is long so it displays in multilines can i display it in single line

**Comment by MuhammadRafeh** [comment]
So you can do this own your own. Please change DatatableRow.js File inside the react-native-datatable-component which is inside node_modules. and give these 2 property below to Text component there which exists on line 53
```js
numberOfLines={1} 
adjustsFontSizeToFit={true}
```

**Comment by MuhammadRafeh** [comment]
node_modules/react-native-datatable-component/src/DataTableRow.js or go directly by press ctrl and click on the import if you are using vs Code it will take you their directly.

**Comment by MuhammadRafeh** [comment]
I hope you got it!
